"""Acquittify top-level system prompt reference.

This module anchors the product-wide narrative that every agent-powered surface must
produce cites that comply with The Bluebook. The actual runtime entry points live in
`trial-discovery-ai/backend` and `trial-discovery-ai/frontend`, but we keep this file so
non-Python tooling (and tests) can quickly assert that the canonical guidance mentions
Bluebook requirements.
"""

from __future__ import annotations

BLUEBOOK_POLICY = (
    "All autogenerated drafts, reports, and agent responses must cite legal authority "
    "using Bluebook-compliant short form and provide the underlying opinion metadata."
)


def describe_policy() -> str:
    """Return the standing citation rule for downstream tooling."""
    return BLUEBOOK_POLICY


if __name__ == "__main__":  # pragma: no cover
    print(BLUEBOOK_POLICY)
